# Generated by Django 3.1.1 on 2020-10-10 16:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='galeria',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='galeria'), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='enlace_juego',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='enlace_video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagenes', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='actualizaciones'), blank=True, null=True, size=None)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='proyectos.proyecto')),
            ],
        ),
    ]
