# Generated by Django 3.1.2 on 2020-10-12 21:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20201010_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacion',
            name='permiso',
            field=models.CharField(choices=[('MI', 'Miembro'), ('AD', 'Administrador'), ('MA', 'Administrador maestro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PR', 'Programador'), ('DI', 'Director'), ('AR', 'Artista'), ('PD', 'Productor'), ('DS', 'Diseñador')], max_length=10), size=None),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fase',
            field=models.CharField(choices=[('PL', 'Planeación'), ('PP', 'Pre-producción'), ('PR', 'Producción'), ('PU', 'Pruebas'), ('PO', 'Post-producción')], max_length=10),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='frameworks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('UN', 'Unity'), ('UR', 'Unreal Engine')], max_length=10), size=None),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='generos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PL', 'Plataforma'), ('PE', 'Pelea'), ('SH', 'Shooter'), ('RP', 'RPG'), ('CA', 'Carreras')], max_length=10), size=None),
        ),
    ]
