# Generated by Django 3.1.1 on 2020-10-27 19:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20201025_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='galeria',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='galeria'), blank=True, default=list, null=True, size=None),
        ),
    ]
