# Generated by Django 3.1.1 on 2020-10-30 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0006_auto_20201027_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='proyectos_seguidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
