# Generated by Django 3.1.1 on 2020-10-31 00:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_proyecto_seguidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='galeria',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, size=None),
        ),
    ]
