# Generated by Django 3.1.1 on 2020-11-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_proyecto_seguidores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='galeria',
        ),
    ]
