# Generated by Django 3.1.1 on 2020-10-31 01:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_auto_20201030_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='galeria',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='galeria'), blank=True, null=True, size=None),
        ),
    ]
