# Generated by Django 3.1.1 on 2020-11-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_auto_20201030_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='galeria',
        ),
    ]
