# Generated by Django 3.1.2 on 2020-10-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='codigo',
            field=models.CharField(default=1000000000, max_length=10),
            preserve_default=False,
        ),
    ]
