# Generated by Django 3.1.2 on 2020-11-02 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0002_conversacion_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacion',
            name='codigo',
        ),
    ]
