# Generated by Django 3.1.1 on 2020-11-04 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_auto_20201103_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='mejorRespuesta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mejorRespuesta', to='preguntas.respuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='puntosNegativos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='puntosPositivos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='puntosNegativos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='puntosPositivos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
