# Generated by Django 3.1.1 on 2020-11-04 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preguntas', '0006_auto_20201104_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='puntosNegativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntasPuntosNegativos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='puntosPositivos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntasPuntosPositivos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='puntosNegativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resouestasPuntosNegativos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='puntosPositivos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestasPuntosPositivos', to=settings.AUTH_USER_MODEL),
        ),
    ]
