# Generated by Django 3.1.1 on 2020-11-05 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preguntas', '0008_auto_20201104_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='puntosNegativos',
            field=models.ManyToManyField(blank=True, related_name='respuestasPuntosNegativos', to=settings.AUTH_USER_MODEL),
        ),
    ]
