# Generated by Django 3.1.1 on 2020-11-17 19:25

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicionVacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PR', 'Programador'), ('DI', 'Director'), ('AR', 'Artista'), ('PD', 'Productor'), ('DS', 'Diseñador')], max_length=2), null=True, size=None)),
                ('frameworks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('UN', 'Unity'), ('UR', 'Unreal Engine')], max_length=2), null=True, size=None)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('aplicantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
