# Generated by Django 3.1.1 on 2020-11-17 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0008_remove_proyecto_galeria'),
        ('posicionVacante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicionvacante',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='proyectos.proyecto'),
        ),
        migrations.AlterField(
            model_name='posicionvacante',
            name='aplicantes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aplicantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
