# Generated by Django 3.1.1 on 2020-11-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posicionVacante', '0002_auto_20201117_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicionvacante',
            name='aplicantes',
        ),
        migrations.RemoveField(
            model_name='posicionvacante',
            name='proyecto',
        ),
    ]
