# Generated by Django 3.1.1 on 2020-11-17 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_remove_proyecto_galeria'),
        ('posicionVacante', '0004_auto_20201117_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicionvacante',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='proyectos.proyecto'),
        ),
    ]
